### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4c/qjnnzbf17w7dbttpwsjr1_vw0000gn/T/pip-build-bioziida/python-mega/

### ISSUE THREAD

**Issue by madchucky** [juanriaza/python-mega#11]
When I try to install the package, I get the following error
`$ pip install python-mega`
```Collecting python-mega
  Using cached python-mega-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4c/qjnnzbf17w7dbttpwsjr1_vw0000gn/T/pip-build-bioziida/python-mega/setup.py", line 48
        print "You probably want to also tag the version now:"
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "You probably want to also tag the version now:")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4c/qjnnzbf17w7dbttpwsjr1_vw0000gn/T/pip-build-bioziida/python-mega/
```
My python version is as follow: 
`$ python --version`
`Python 3.6.3 :: Anaconda, Inc.`

**Comment by madchucky** [comment]
Sorry, it is linked to [Python 3 support](https://github.com/juanriaza/python-mega/issues/10).

**Comment by JuanjoSalvador** [comment]
You can use a `virtualenv` with Python 2.7 and install it using pip. I'm using python-mega on a small script for scrap and download a lot of links into a webpage and it works fine.

Support for Python 3 will come in few weeks, I have a lot of work and I only can code my own things on weekends.
